"use strict";
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
exports.__esModule = true;
exports.Attributes__factory = void 0;
var ethers_1 = require("ethers");
var _abi = [
    {
        inputs: [
            {
                internalType: "uint256",
                name: "",
                type: "uint256"
            },
        ],
        name: "ability_scores",
        outputs: [
            {
                internalType: "uint32",
                name: "",
                type: "uint32"
            },
            {
                internalType: "uint32",
                name: "",
                type: "uint32"
            },
            {
                internalType: "uint32",
                name: "",
                type: "uint32"
            },
            {
                internalType: "uint32",
                name: "",
                type: "uint32"
            },
            {
                internalType: "uint32",
                name: "",
                type: "uint32"
            },
            {
                internalType: "uint32",
                name: "",
                type: "uint32"
            },
        ],
        stateMutability: "view",
        type: "function"
    },
    {
        inputs: [
            {
                internalType: "uint256",
                name: "",
                type: "uint256"
            },
        ],
        name: "character_created",
        outputs: [
            {
                internalType: "bool",
                name: "",
                type: "bool"
            },
        ],
        stateMutability: "view",
        type: "function"
    },
];
var Attributes__factory = /** @class */ (function () {
    function Attributes__factory() {
    }
    Attributes__factory.createInterface = function () {
        return new ethers_1.utils.Interface(_abi);
    };
    Attributes__factory.connect = function (address, signerOrProvider) {
        return new ethers_1.Contract(address, _abi, signerOrProvider);
    };
    Attributes__factory.abi = _abi;
    return Attributes__factory;
}());
exports.Attributes__factory = Attributes__factory;
