/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  CodexBaseRandom,
  CodexBaseRandomInterface,
} from "../CodexBaseRandom";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_summoner",
        type: "uint256",
      },
    ],
    name: "d20",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class CodexBaseRandom__factory {
  static readonly abi = _abi;
  static createInterface(): CodexBaseRandomInterface {
    return new utils.Interface(_abi) as CodexBaseRandomInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): CodexBaseRandom {
    return new Contract(address, _abi, signerOrProvider) as CodexBaseRandom;
  }
}
