"use strict";
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
exports.__esModule = true;
exports.RarityAttributes__factory = void 0;
var ethers_1 = require("ethers");
var _abi = [
    {
        inputs: [
            {
                internalType: "uint256",
                name: "",
                type: "uint256"
            },
        ],
        name: "ability_scores",
        outputs: [
            {
                internalType: "uint32",
                name: "",
                type: "uint32"
            },
            {
                internalType: "uint32",
                name: "",
                type: "uint32"
            },
            {
                internalType: "uint32",
                name: "",
                type: "uint32"
            },
            {
                internalType: "uint32",
                name: "",
                type: "uint32"
            },
            {
                internalType: "uint32",
                name: "",
                type: "uint32"
            },
            {
                internalType: "uint32",
                name: "",
                type: "uint32"
            },
        ],
        stateMutability: "view",
        type: "function"
    },
    {
        inputs: [
            {
                internalType: "uint256",
                name: "score",
                type: "uint256"
            },
        ],
        name: "calc",
        outputs: [
            {
                internalType: "uint256",
                name: "",
                type: "uint256"
            },
        ],
        stateMutability: "pure",
        type: "function"
    },
];
var RarityAttributes__factory = /** @class */ (function () {
    function RarityAttributes__factory() {
    }
    RarityAttributes__factory.createInterface = function () {
        return new ethers_1.utils.Interface(_abi);
    };
    RarityAttributes__factory.connect = function (address, signerOrProvider) {
        return new ethers_1.Contract(address, _abi, signerOrProvider);
    };
    RarityAttributes__factory.abi = _abi;
    return RarityAttributes__factory;
}());
exports.RarityAttributes__factory = RarityAttributes__factory;
