/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { Rarity, RarityInterface } from "../Rarity";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    name: "class",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    name: "getApproved",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    name: "level",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    name: "ownerOf",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_summoner",
        type: "uint256",
      },
    ],
    name: "summoner",
    outputs: [
      {
        internalType: "uint256",
        name: "_xp",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_log",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_class",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_level",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class Rarity__factory {
  static readonly abi = _abi;
  static createInterface(): RarityInterface {
    return new utils.Interface(_abi) as RarityInterface;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): Rarity {
    return new Contract(address, _abi, signerOrProvider) as Rarity;
  }
}
