"use strict";
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var __extends = (this && this.__extends) || (function () {
    var extendStatics = function (d, b) {
        extendStatics = Object.setPrototypeOf ||
            ({ __proto__: [] } instanceof Array && function (d, b) { d.__proto__ = b; }) ||
            function (d, b) { for (var p in b) if (Object.prototype.hasOwnProperty.call(b, p)) d[p] = b[p]; };
        return extendStatics(d, b);
    };
    return function (d, b) {
        if (typeof b !== "function" && b !== null)
            throw new TypeError("Class extends value " + String(b) + " is not a constructor or null");
        extendStatics(d, b);
        function __() { this.constructor = d; }
        d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
    };
})();
exports.__esModule = true;
exports.Timestamp__factory = void 0;
var ethers_1 = require("ethers");
var _abi = [
    {
        inputs: [],
        name: "getTimestamp",
        outputs: [
            {
                internalType: "uint256",
                name: "",
                type: "uint256"
            },
        ],
        stateMutability: "view",
        type: "function"
    },
];
var _bytecode = "0x608060405234801561001057600080fd5b5060b58061001f6000396000f3fe6080604052348015600f57600080fd5b506004361060285760003560e01c8063188ec35614602d575b600080fd5b60336047565b604051603e9190605c565b60405180910390f35b600042905090565b6056816075565b82525050565b6000602082019050606f6000830184604f565b92915050565b600081905091905056fea26469706673582212204de76773a66afb929e66f35716fda89190ca8954153c0d1a41d502a657a81eb064736f6c63430008070033";
var Timestamp__factory = /** @class */ (function (_super) {
    __extends(Timestamp__factory, _super);
    function Timestamp__factory(signer) {
        return _super.call(this, _abi, _bytecode, signer) || this;
    }
    Timestamp__factory.prototype.deploy = function (overrides) {
        return _super.prototype.deploy.call(this, overrides || {});
    };
    Timestamp__factory.prototype.getDeployTransaction = function (overrides) {
        return _super.prototype.getDeployTransaction.call(this, overrides || {});
    };
    Timestamp__factory.prototype.attach = function (address) {
        return _super.prototype.attach.call(this, address);
    };
    Timestamp__factory.prototype.connect = function (signer) {
        return _super.prototype.connect.call(this, signer);
    };
    Timestamp__factory.createInterface = function () {
        return new ethers_1.utils.Interface(_abi);
    };
    Timestamp__factory.connect = function (address, signerOrProvider) {
        return new ethers_1.Contract(address, _abi, signerOrProvider);
    };
    Timestamp__factory.bytecode = _bytecode;
    Timestamp__factory.abi = _abi;
    return Timestamp__factory;
}(ethers_1.ContractFactory));
exports.Timestamp__factory = Timestamp__factory;
