/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomiclabs/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "RarityAttributes",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.RarityAttributes__factory>;
    getContractFactory(
      name: "Rarity",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Rarity__factory>;
    getContractFactory(
      name: "Codex",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Codex__factory>;
    getContractFactory(
      name: "Attributes",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Attributes__factory>;
    getContractFactory(
      name: "CodexBaseRandom",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.CodexBaseRandom__factory>;
    getContractFactory(
      name: "Ownable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Ownable__factory>;
    getContractFactory(
      name: "RarityBattle",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.RarityBattle__factory>;
    getContractFactory(
      name: "RarityGold",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.RarityGold__factory>;
    getContractFactory(
      name: "Rarity",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Rarity__factory>;
    getContractFactory(
      name: "Greeter",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Greeter__factory>;
    getContractFactory(
      name: "CodexBaseRandom",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.CodexBaseRandom__factory>;
    getContractFactory(
      name: "League",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.League__factory>;
    getContractFactory(
      name: "MatchMaker",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MatchMaker__factory>;
    getContractFactory(
      name: "Rarity",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Rarity__factory>;
    getContractFactory(
      name: "RarityAttributes",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.RarityAttributes__factory>;
    getContractFactory(
      name: "ERC721",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC721__factory>;
    getContractFactory(
      name: "ERC721Enumerable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC721Enumerable__factory>;
    getContractFactory(
      name: "IERC721",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC721__factory>;
    getContractFactory(
      name: "IERC721Enumerable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC721Enumerable__factory>;
    getContractFactory(
      name: "IERC721Receiver",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC721Receiver__factory>;
    getContractFactory(
      name: "Rarity",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Rarity__factory>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.utils.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
  }
}
